[package]
name = "slimmer_box"
version = "0.1.0"
edition = "2021"

[dependencies]
ptr_meta = { version = "0.2.0", default_features = false }
rkyv = { version = "0.7.39", features = [], optional = true }

[features]
std = []
rkyv = [ "dep:rkyv" ]